version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install black
            black --check --line-length 80 */*.py
            pip install -r dev-requirements.txt
            pip install -e .
            pytest tests
